module.exports = {
  ORDER_STATUS: {
    CREATED: 'created',
    PENDING_PAYMENT: 'pending_payment',
    CONFIRMED: 'confirmed',
    SHIPPED: 'shipped',
    OUT_FOR_DELIVERY: 'out_for_delivery',
    DELIVERED: 'delivered',
    ON_HOLD: 'on_hold',
    FAILED: 'failed',
    CANCELLED: 'cancelled',
    RETURNED: 'returned',
    REFUNDED: 'refunded',
  },
  ORDER_STATUS_LIST: [
    'created',
    'pending_payment',
    'confirmed',
    'shipped',
    'out_for_delivery',
    'delivered',
    'on_hold',
    'failed',
    'cancelled',
    'returned',
    'refunded',
  ],
  ADMIN_STATUS_UPDATES: [
    'pending_payment',
    'confirmed',
    'shipped',
    'out_for_delivery',
    'delivered',
    'on_hold',
    'failed',
    'cancelled',
    'returned',
    'refunded',
  ],
  ORDER_ITEM_TRANSITIONS: {
    created: ['confirmed', 'cancelled', 'on_hold'],
    confirmed: ['packed', 'cancelled', 'on_hold'],
    packed: ['shipped', 'on_hold'],
    shipped: ['out_for_delivery', 'delivered', 'returned', 'on_hold'],
    out_for_delivery: ['delivered', 'returned', 'on_hold'],
    delivered: ['returned'],
    on_hold: ['confirmed', 'shipped', 'cancelled'],
    cancelled: [],
    returned: ['refunded'],
    refunded: [],
  },
};
